version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: pgvector/pgvector:pg17
    container_name: core_agent_postgres
    environment:
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_pass
      POSTGRES_DB: agent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core_agent_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis/redis-stack:latest
    container_name: core_agent_redis
    environment:
      - REDIS_ARGS=--requirepass redis_password
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight
    volumes:
      - redis_data:/data
    networks:
      - core_agent_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a redis_password --no-auth-warning ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: