version: '3.8'

services:
  # Redis service for memory storage
  redis:
    image: redis:7-alpine
    container_name: coreagent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - coreagent_network

  # CoreAgent application
  coreagent_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: coreagent_app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_VERSION=2023-12-01-preview
      - AZURE_OPENAI_ENDPOINT=https://oai-202-fbeta-dev.openai.azure.com/
      - OPENAI_API_KEY=BDfLqbP0vVCTuRkXtE4Zy9mK7neLrJlHXlISgqJxVNTg2ca71EI5JQQJ99BDACOGgIx4
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker if needed
    networks:
      - coreagent_network
    command: python test_redis_memory.py

  # Redis CLI for debugging (optional)
  redis_cli:
    image: redis:7-alpine
    container_name: coreagent_redis_cli
    depends_on:
      - redis
    networks:
      - coreagent_network
    command: ["redis-cli", "-h", "redis", "-p", "6379"]
    profiles:
      - debug

  # Memory test runner
  memory_test:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: coreagent_memory_test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_VERSION=2023-12-01-preview
      - AZURE_OPENAI_ENDPOINT=https://oai-202-fbeta-dev.openai.azure.com/
      - OPENAI_API_KEY=BDfLqbP0vVCTuRkXtE4Zy9mK7neLrJlHXlISgqJxVNTg2ca71EI5JQQJ99BDACOGgIx4
    volumes:
      - .:/app
    networks:
      - coreagent_network
    command: python test_comprehensive_redis_memory.py
    profiles:
      - test

volumes:
  redis_data:
    driver: local

networks:
  coreagent_network:
    driver: bridge